### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by daas-ankur-shukla** [daas-ankur-shukla/SOSClient#1]
**List of tasks for SOSClient Project**

**Javascript UI**

- [ ] Display Leaflet Map
- [ ] Connect JS UI with Postgres
- [ ] ...

**Backend Python App**

- [ ] Dump NDBC data in postgres database

**Comment by daas-ankur-shukla** [comment]
**Current Status**

![screen02](https://user-images.githubusercontent.com/20864366/38395674-bd1482be-3951-11e8-9541-20976766ecab.gif)
