### ISSUE TITLE
My Task list 

### ISSUE THREAD

**Issue by omshinde** [daas-ankur-shukla/SOSClient#2]
List of tasks for SOSClient: @omshinde
Include points to ponder for the problems faced

- [x] Create a map on the ui using leaflet API.

- Change the MapBox studio api key to the OSM. Otherwise login to the MapBox studio. Solved by @daas-ankur-shukla 

- [x] Connecting Postgres to display data on map
- Install [postgREST](https://postgrest.com/en/v4.4/tutorials/tut0.html#step-3-install-postgrest).
- Setup postgREST by making a .conf file. Include db-uri, db-schema, db-anon-role (annotated role).
- Access the relation by opening  http://localhost:3000/{relation_name}

Backend:
- [ ] Download NDBC data and store it in postgres database in real time

**Comment by daas-ankur-shukla** [comment]
@omshinde please add todays class notes snapshot for guide on the requirements
